import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { UserContextProvider } from "@/context/userContext";
import { AdminContextProvider } from "@/context/adminContext";
import { AppModeContextProvider } from "@/context/appMode";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <AdminContextProvider>
            <UserContextProvider>
        <AppModeContextProvider>
          {children}
           </AppModeContextProvider>
            </UserContextProvider>
        </AdminContextProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
